
auth.token=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

defaults.org=unhinged
defaults.project=unhinged-app

defaults.url=https://sentry.io/
